### ISSUE TITLE
RS485 definitions structure

### ISSUE THREAD

**Issue by 0x72D0** [sonia-auv/hardware-utility-auv8#2]
Since the boards structure change with AUV8, we need to change the structure of the RS485 definition.

This thread purpose is to reference and discuss all the changes with the RS485 definition.

**Comment by 0x72D0** [comment]
I suggest this structure for base:

```//###################################################
//              SLAVE DEFINITION
//###################################################

#define SLAVE_powersupply0 0
#define SLAVE_powersupply1 1
#define SLAVE_powersupply2 2
#define SLAVE_powersupply3 3
#define SLAVE_killMission 4
#define SLAVE_ESC 5
#define SLAVE_IO_CTR 6
#define SLAVE_LED_SCREEN 7

//###################################################
//              CMD DEFINITION
//###################################################

// define kill mission switch
#define CMD_MISSION 0
#define CMD_KILL 1

// define powersupply
#define CMD_PS_V16_1 0
#define CMD_PS_V16_2 1
#define CMD_PS_V12 2

#define CMD_PS_C16_1 3
#define CMD_PS_C16_2 4
#define CMD_PS_C12 5

#define CMD_PS_temperature 6
#define CMD_PS_VBatt 7

#define CMD_PS_ACT_12V 8
#define CMD_PS_ACT_16V_1 9
#define CMD_PS_ACT_16V_2 10

#define CMD_PS_CHECK_12V 11
#define CMD_PS_CHECK_16V_1 12
#define CMD_PS_CHECK_16V_2 13

// define ESC
#define CMD_ESC_MOTOR_1 0
#define CMD_ESC_MOTOR_2 1
#define CMD_ESC_MOTOR_3 2
#define CMD_ESC_MOTOR_4 3
#define CMD_ESC_MOTOR_5 4
#define CMD_ESC_MOTOR_6 5
#define CMD_ESC_MOTOR_7 6
#define CMD_ESC_MOTOR_8 7

// define IO CONTROL
#define CMD_IO_TEMP  0
#define CMD_IO_DROPPER_ACTION  1
#define CMD_IO_TORPEDO_ACTION  2
#define CMD_IO_ARM_ACTION 3

//###################################################
//              DATA DEFINITION
//###################################################

#define DATA_IO_DROPPER_PORT 0
#define DATA_IO_DROPPER_STARBOARD 1

#define DATA_IO_TORPEDO_PORT 0
#define DATA_IO_TORPEDO_STARBOARD 1

#define DATA_IO_ARM_CLOSE 0
#define DATA_IO_ARM_OPEN 1

**Comment by 0x72D0** [comment]
@supertoto29 can you confirm me that we can delete the kill switch in RS485 because it's doesn't propagate on RS485 anymore?

**Comment by 0x72D0** [comment]
@supertoto29 can you also confirm the command, I'm not sure about them.

**Comment by supertoto29** [comment]
It's good keep everything

**Comment by 0x72D0** [comment]
@coumarc9 is it good on the software side?

**Comment by supertoto29** [comment]
Finally I removed these 2 commands on the powersupply. There aren't needed anymore.

CMD_PS_ACT_12V
CMD_PS_CHECK_12V

**Comment by marcantoinecouture** [comment]
I not sure a understand how communication will work with ESC.
Actually, a single message containing the ESC slave, the ESC command and 8 bytes of data, which corresponds to the 8 thrusters. This allows using a variable number of thrusters on the submarine, good for us and in case another team uses our code. (Note: in the current definition, there are 9 slaves, but only one is used.)
On the new definition, you propose 8 commands for the ESC (one for each). Is it an error or this is where the electrical team wants to program their new ESC interfaces?

**Comment by supertoto29** [comment]
These definition were taken from the old RS485 definition. They were already there but for us, it is not useful. We only use one command with the 8 bytes of data to update all the thrusters.
So we should remove it?

**Comment by 0x72D0** [comment]
yeah I'm gonna remove them

**Comment by 0x72D0** [comment]
@coumarc9 I also have a question for the IO board, because we are using a RTOS in the electrical architecture, you can see each command as a different thread. It make sense if we do a different command for Torpido_port and Torpido_starboard and a different command for Dropper_port and Dropper_starboard, but does it make sense if we do a different command for ARM_open and ARM_close? Or it would be better to have ARM_action and close and open via the data?

**Comment by supertoto29** [comment]
@0x72D0 Closing this issue since the structure has been changed and this issue is not relavent with the actual structure.
